In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
a=np.array([100,200,300])
b=np.array([(100.5,200,300), (400,500,600)], dtype = float)
c=np.array([[(100.5,200,300), (400,500,600)],[(300,200,100), (400,500,600)]], dtype = float)

In [7]:
print(a)
print(b)
print(c)

[100 200 300]
[[100.5 200.  300. ]
 [400.  500.  600. ]]
[[[100.5 200.  300. ]
  [400.  500.  600. ]]

 [[300.  200.  100. ]
  [400.  500.  600. ]]]


In [9]:
np.ones((50))#rows

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.zeros((30,40))#rows,cols

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
np.ones((20,30,40))#shapes , rows, cols

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       ...,

       [[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1.

In [17]:
d=np.arange(70,250,30)
print(d)

[ 70 100 130 160 190 220]


In [19]:
np.linspace(0,111,777)

array([  0.        ,   0.14304124,   0.28608247,   0.42912371,
         0.57216495,   0.71520619,   0.85824742,   1.00128866,
         1.1443299 ,   1.28737113,   1.43041237,   1.57345361,
         1.71649485,   1.85953608,   2.00257732,   2.14561856,
         2.28865979,   2.43170103,   2.57474227,   2.71778351,
         2.86082474,   3.00386598,   3.14690722,   3.28994845,
         3.43298969,   3.57603093,   3.71907216,   3.8621134 ,
         4.00515464,   4.14819588,   4.29123711,   4.43427835,
         4.57731959,   4.72036082,   4.86340206,   5.0064433 ,
         5.14948454,   5.29252577,   5.43556701,   5.57860825,
         5.72164948,   5.86469072,   6.00773196,   6.1507732 ,
         6.29381443,   6.43685567,   6.57989691,   6.72293814,
         6.86597938,   7.00902062,   7.15206186,   7.29510309,
         7.43814433,   7.58118557,   7.7242268 ,   7.86726804,
         8.01030928,   8.15335052,   8.29639175,   8.43943299,
         8.58247423,   8.72551546,   8.8685567 ,   9.01

In [32]:
e=np.full((666),999)
print(e)
print(e.ndim)

[999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999 999
 999 999 999 999 999 999 999 999 999 999 999 999 99

In [34]:
e=np.full((22,222),999)
print(e)
print(e.ndim)

[[999 999 999 ... 999 999 999]
 [999 999 999 ... 999 999 999]
 [999 999 999 ... 999 999 999]
 ...
 [999 999 999 ... 999 999 999]
 [999 999 999 ... 999 999 999]
 [999 999 999 ... 999 999 999]]
2


In [36]:
e=np.full((222,222,222),999)
print(e)
print("no of demension: ",e.ndim)

[[[999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  ...
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]]

 [[999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  ...
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]]

 [[999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  ...
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]]

 ...

 [[999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  ...
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]]

 [[999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  ...
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 999]
  [999 999 999 ... 999 999 9

In [38]:
f=np.eye(444)
print(f)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [40]:
np.random.random((222,333))

array([[0.61462646, 0.55626938, 0.38229942, ..., 0.08410379, 0.07720261,
        0.4553524 ],
       [0.88336174, 0.08230992, 0.96099621, ..., 0.59337086, 0.28035673,
        0.68954156],
       [0.69501888, 0.28707467, 0.59827743, ..., 0.29295445, 0.70557115,
        0.05636827],
       ...,
       [0.21741485, 0.23903374, 0.01100321, ..., 0.04001218, 0.97555505,
        0.10539466],
       [0.42336728, 0.6534315 , 0.70000623, ..., 0.39369395, 0.99111884,
        0.08093414],
       [0.52036349, 0.64606049, 0.98651499, ..., 0.98364825, 0.78779002,
        0.32027962]])

In [54]:
np.random.randint(111,100111)

94576

In [56]:
arr=np.array([[11,22,33,44],
              [55,66,77,88,],
              [99,100,111,122]])
print(arr.shape)

(3, 4)


In [58]:

arr=np.array([[11,22,33,44],
              [55,66,77,88,],
              [99,100,111,122]])
print(arr.size)

12


In [62]:
arr=np.array([[11,22,33,44],
              [55,66,77,88,],
              [99,100,111,122]])
len(